/*
Notes: 
- FlatID may need to be generated by javascript on inserts
*/

-- Instances represent a user (flatmate)
create table User (
    Email varchar(30) not null unique,
    Username varchar(30) not null unique,
    Password varchar(15) not null,
    FlatID varchar(10),
    constraint User_PK primary key (Email),
    constraint Flat_FK foreign key (FlatID)
        references (Flat.FlatID)
);

-- Instances represent a flat shared between Users
create table Flat (
    FlatID varchar(10) not null unique,
    Address varchar(50),
    constraint Flat_PK primary key (FlatID)
);

-- Instances represent an Event happening at some point in time
-- A flat can have multiple events, an event must be associated with a flat
create table Event (
    EventID int not null unique auto_increment,
    FlatID varchar(10) not null,
    Title varchar(40),
    Description varchar(150),
    Event_Date date,
    Start_Time time,
    End_Time time,
    constraint Event_PK primary key (EventID, FlatID),
    constraint Flat_FK foreign key (FlatID)
        references (Flat.FlatID)
);

-- Instances represnt a flat bill / expense
-- A flat can have multiple bills, a bill must be associated with a flat
create table Bills (
    BillID int not null unique auto_increment,
    FlatID varchar(10) not null,
    Ammount decimal(7, 2),
    Description varchar(150),
    constraint Bills_PK primary key (FlatID, BillID),
    constraint Flat_FK foreign key (FlatID)
        references (Flat.FlatID),
    constraint Ammount_CHK check (Ammount >= 0)
);

-- Instances represent grocery items for grocery list 
-- A flat can have multiple groceries, a grocery item must be associated with a flat
create table Groceries (
    FlatID varchar(10) not null,
    Item varchar(30) unique not null,
    Price decimal(7, 2),
    Qty int,
    constraint Grocery_PK primary key (FlatID, Item),
    constraint Flat_FK foreign key (FlatID)
        references (Flat.FlatID),
    constraint Price_Qty_CHK check (Qty > 0 and Price > 0)
);

-- Instances represent jobs / chores to do for chore list
-- A Flat can have multiple chores, a chore must be associated with a flat
create table Chores (
    FlatID varchar(10) not null,
    ChoreID int not null unique auto_increment,
    Priority varchar(30),
    Title varchar(30),
    Description varchar(150),
    constraint Chore_PK primary key (FlatID, ChoreID),
    constraint Flat_FK foreign key (FlatID)
        references (Flat.FlatID)
);

-- Table represents relationship between Users and Chores
-- A user can have multiple chores and chores can have multiple users
create table Chore_Assignment (
    UserID varchar(30) not null,
    ChoreID int not null,
    constraint Chore_Assignment_PK primary key (UserID, ChoreID),
    constraint User_FK foreign key (UserID)
        references (User.Email),
    constraint Chore_FK foreign key (ChoreID)
        references (Chores.ChoreID)
);

-- Table represents relationship between Users and Events
-- A user can have multiple events and an event can have multiple users
create table Users_Events (
    UserID varchar(30) not null,
    EventID int not null,
    constraint Users_Events_PK primary key (UserID, EventID),
    constraint User_FK foreign key (UserID)
        references (User.Email),
    constraint Event_FK foreign key (EventID)
        references (Event.EventID)
);

